apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSQL_DATABASE: "tlc"
  MYSQL_USER: "tlc"
  quarkus_datasource_jdbc_url: "jdbc:mysql://mysql-service:3306/tlc?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Paris"
  quarkus_datasource_username: "tlc"
  quarkus_hibernate_orm_database_generation: "update"
  quarkus_mailer_from: "olivier.barais@gmail.com"
  quarkus_mailer_host: "mail-service"
  quarkus_mailer_port: "25"
  quarkus_mailer_ssl: "false"
  quarkus_mailer_username: ""
  quarkus_mailer_password: ""
  quarkus_mailer_mock: "true"
  doodle_usepad: "false"
  doodle_padUrl: "http://etherpad-service:9001/"
  doodle_organizermail: "olivier.barais@gmail.com"
