apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_PASSWORD: "tlc"
  quarkus_datasource_password: "tlc"
  doodle_padApiKey: "changeit"
  GF_SECURITY_ADMIN_PASSWORD: "adminpassword"
