apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_PASSWORD: "tlc"
  quarkus_datasource_password: "tlc"
  doodle_padApiKey: "19d89ca52bc0fa4f19d6325464d9d7a032649b9fa68c111514627081e2784b4a"
  GF_SECURITY_ADMIN_PASSWORD: "adminpassword"
