version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  etherpad:
    image: etherpad/etherpad
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    networks:
      - app-network

  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - app-network

  backend:
    image: paulkourouma/tlc-backend:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      etherpad:
        condition: service_started
      mail:
        condition: service_started
    environment:
      - quarkus_datasource_jdbc_url=jdbc:mysql://db:3306/tlc?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Paris
      - quarkus_datasource_username=tlc
      - quarkus_datasource_password=tlc
      - quarkus_hibernate_orm_database_generation=update
      - quarkus_mailer_from=olivier.barais@gmail.com
      - quarkus_mailer_host=mail
      - quarkus_mailer_port=25
      - quarkus_mailer_ssl=false
      - quarkus_mailer_username=""
      - quarkus_mailer_password=""
      - quarkus_mailer_mock=true
      - doodle_usepad=false
      - doodle_padUrl=http://etherpad:9001/
      - doodle_padApiKey=changeit
      - doodle_organizermail=olivier.barais@gmail.com
    networks:
      - app-network

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: paulkourouma/tlc-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - myadmin
      - etherpad
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    networks:
      - app-network
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - frontend
    # Pour le test, on va utiliser la commande "--dry-run"
    # Une fois testé, vous pouvez retirer "--dry-run"
    command: certonly --webroot --webroot-path=/var/www/certbot
             --email paulledadj@gmail.com --agree-tos --no-eff-email
             --force-renewal
             -d doodle.paulkourouma.com -d myadmin.paulkourouma.com -d pad.paulkourouma.com

networks:
  app-network:

volumes:
  mysql_data:
